INSERT INTO empleados (id, nombre, apellidos, email, telefono, area_dep, cargo, activo) VALUES(1, 'Alecia', 'Snufflebottom', 'asnufflebottom0@cam.ac.uk', '193029944', 'Services', 'Accountant I', true);
INSERT INTO empleados (id, nombre, apellidos, email, telefono, area_dep, cargo, activo) VALUES(2, 'Brennan', 'Veschambre', 'bveschambre1@patch.com', '193029944''Marketing', 'Executive Secretary', true);
INSERT INTO empleados (id, nombre, apellidos, email, telefono, area_dep, cargo, activo) VALUES(3, 'Westbrooke', 'Josum', 'wjosum2@hubpages.com', '193029944''Support', 'Quality Control Specialist', true);
INSERT INTO empleados (id, nombre, apellidos, email, telefono, area_dep, cargo, activo) VALUES(4, 'Giordano', 'Bilton', 'gbilton3@icq.com', '193029944''Legal', 'Project Manager', false);
INSERT INTO empleados (id, nombre, apellidos, email, telefono, area_dep, cargo, activo) VALUES(5, 'Nevins', 'Godthaab', 'ngodthaab4@alibaba.com', '193029944''Support', 'Office Assistant I', true);
INSERT INTO empleados (id, nombre, apellidos, email, telefono, area_dep, cargo, activo) VALUES(6, 'Burnard', 'Moorman', 'bmoorman5@chicagotribune.com', '193029944''Accounting', 'Staff Accountant III', false);
INSERT INTO empleados (id, nombre, apellidos, email, telefono, area_dep, cargo, activo) VALUES(7, 'Reilly', 'Skiplorne', 'rskiplorne6@scientificamerican.com', '193029944''Product Management', 'VP Sales', false);
INSERT INTO empleados (id, nombre, apellidos, email, telefono, area_dep, cargo, activo) VALUES(8, 'Isador', 'Milnthorpe', 'imilnthorpe7@simplemachines.org', '193029944''Legal', 'Software Test Engineer IV', true);
INSERT INTO empleados (id, nombre, apellidos, email, telefono, area_dep, cargo, activo) VALUES(9, 'Betteanne', 'Fancy', 'bfancy8@unc.edu', '193029944''Support', 'Tax Accountant', false);
INSERT INTO empleados (id, nombre, apellidos, email, telefono, area_dep, cargo, activo) VALUES(10, 'Shell', 'Lyall', 'slyall9@list-manage.com', '193029944', 'Business Development', 'Occupational Therapist', false);
INSERT INTO empleados (id, nombre, apellidos, email, telefono, area_dep, cargo, activo) VALUES(11, 'Seamus', 'Villalta', 'svillaltaa@deviantart.com', '193029944', 'Engineering', 'Sales Associate', true);
INSERT INTO empleados (id, nombre, apellidos, email, telefono, area_dep, cargo, activo) VALUES(12, 'Mayne', 'Vela', 'mvelab@kickstarter.com', '193029944', 'Accounting', 'Junior Executive', false);
INSERT INTO empleados (id, nombre, apellidos, email, telefono, area_dep, cargo, activo) VALUES(13, 'Odele', 'Sherrington', 'osherringtonc@flickr.com', '193029944', 'Services', 'Information Systems Manager', true);
INSERT INTO empleados (id, nombre, apellidos, email, telefono, area_dep, cargo, activo) VALUES(14, 'Morlee', 'Beaudry', 'mbeaudryd@usda.gov', '193029944', 'Training', 'Senior Developer', true);
INSERT INTO grupos (id,nombre) VALUES(1, 'front_developers');
INSERT INTO grupos (id,nombre) VALUES(1, 'back-developers');
INSERT INTO proyectos (id,nombre) VALUES(1, 'Proyecto Microsoft');
INSERT INTO proyectos (id,nombre) VALUES(1, 'Proyecto IBM');
INSERT INTO proyectos (id,nombre) VALUES(1, 'Proyecto Movistar');
INSERT INTO proyectos (id,nombre) VALUES(1, 'Proyecto Realmadrid FC');
